server:
  port: 8080
#gzmu:
#  social:
#    qq:
#      app-id: 123456
#      app-secret: 654321
#      provider-id: 654321
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/lesson-cloud?useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&autoReconnect=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat,wall
      initial-size: 5
      max-active: 20
      max-pool-prepared-statement-per-connection-size: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 30000
      min-idle: 5
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      use-global-data-source-stat: true
      validation-query: select 'x'
      stat-view-servlet:
        enabled: true
        login-password: 123456
        login-username: admin
        url-pattern: /druid/*
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  data:
    rest:
      default-page-size: 10
  jpa:
    show-sql: true
    properties:
#      redisson-config: redisson.yaml
#      redis:
#        expiryInSeconds:
#          default: 120
#          hibernate:
#            common: 0
#            account: 1200
      hibernate:
        cache:
          redisson:
            config: redisson.yaml
          region:
            factory_class: org.redisson.hibernate.RedissonRegionFactory
          region_prefix: gzmu_lesson_cloud_
          use_query_cache: true
          use_second_level_cache: true
          use_structured_entries: true
        format_sql: true
        generate_statistics: false
        javax:
          cache:
            missing_cache_strategy: create
  mail:
    host: smtp.exmail.qq.com
    port: 465
    username: lessonCloud@japoul.cn
    password: lessonC2019
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          starttls:
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
    test-connection: false
  redis:
    host: 127.0.0.1
    password:
management:
  endpoints:
    web:
      exposure:
        include: "*"

application:
  security:
    enabled: false
    authorization-server-url: http://118.24.1.170:8888
  message:
    app-id: 35223
    app-key: e7eede1811867421882df861a20ed26e
    action-template: RhXa


security:
  oauth2:
    resource:
      token-info-uri: http://118.24.1.170:8888/oauth/check_token
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvy4bBhT5RpWt+jMOpqQA
          /Ln3ja2AhJbEn/DLBXyE6SsgmJoHJjqotIVTTGcg7cRbERuMbc7rzd6P00FgsOTq
          YnxZCOBRSugzZ7kdfD2vHtQOP1wVvm8Dew/zDdHS2NHeDGnOO0m/4DXuwlT4tFXe
          wQcYiY+g/n+px7EhJI8Lk9lTR2XT65AYF/NNtZIMbiICAduOjgfS2i3soOulPj4V
          xyyG55HKOkBsbK4NJFQce/j2qRV6pRM9ZptMbBurlMzmO0NHdHVCKs1jyKLsV8BD
          j6YHPihuc3fA96yri+c51PRjqPeS7SXCjyqjdbvsYKSCL4Z7XNJ7izsx9Prn6N4J
          awIDAQAB
          -----END PUBLIC KEY-----
        key-uri: http://118.24.1.170:8888/oauth/token_key
    client:
      access-token-uri: http://118.24.1.170:8888/oauth/token
      client-id: lesson-cloud
      client-secret: lesson-cloud-secret
      grant-type: password,refresh_token,sms,email,authorization_code
      scope: all


logging:
  level:
    org:
      springframework:
        security: debug
