server:
  port: 8080
#gzmu:
#  social:
#    qq:
#      app-id: 123456
#      app-secret: 654321
#      provider-id: 654321
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/lesson-cloud?useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&autoReconnect=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat,wall
      initial-size: 5
      max-active: 20
      max-pool-prepared-statement-per-connection-size: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 30000
      min-idle: 5
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      use-global-data-source-stat: true
      validation-query: select 'x'
      stat-view-servlet:
        enabled: true
        login-password: 123456
        login-username: admin
        url-pattern: /druid/*

  jpa:
    show-sql: true
    properties:
#      redisson-config: redisson.yaml
#      redis:
#        expiryInSeconds:
#          default: 120
#          hibernate:
#            common: 0
#            account: 1200
      hibernate:
        cache:
          redisson:
            config: redisson.yaml
          region:
            factory_class: org.redisson.hibernate.RedissonRegionFactory
          region_prefix: gzmu_lesson_cloud_
          use_query_cache: true
          use_second_level_cache: true
          use_structured_entries: true
        format_sql: true
        generate_statistics: false
        javax:
          cache:
            missing_cache_strategy: create

  redis:
    host: 127.0.0.1
    password:
management:
  endpoints:
    web:
      exposure:
        include: "*"

security:
  oauth2:
    client:
      client-secret: gzmuSecret
      client-id: gzmu
      registered-redirect-uri: http://example.com
#logging:
#  level:
#    org: debug
